# Generated by Django 6.0.2 on 2026-02-11 16:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "builtin_memory",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "price_regular",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("price_sale", models.CharField(blank=True, max_length=11, null=True)),
                ("sku", models.CharField(blank=True, max_length=50, null=True)),
                ("reviews_count", models.IntegerField(blank=True, null=True)),
                (
                    "images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                    ),
                ),
                ("characteristics", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
