# Generated by Django 6.0.2 on 2026-02-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="status",
            field=models.CharField(
                choices=[("NW", "New"), ("DE", "Done"), ("FD", "Failed")],
                default="NW",
                max_length=2,
            ),
        ),
    ]
