# Generated by Django 6.0.2 on 2026-02-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_app", "0002_productinfo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="screen_diagonal",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="productinfo",
            name="screen_resolution",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
